import { useState } from 'react';
import { Archive, Check, Plus, Users } from 'lucide-react';
import { routes } from '../app/routes';
import { useNavigate } from 'react-router-dom';
import { DATA_SCOPES, PERMISSION_ACTIONS, type DataScope, type Role } from '../types/v1';
import { rolePermissions } from '../state/authorization';
import { ActionMenu, Alert, Badge, Button, Card, DataTable, DemoNotice, EmptyState, FilterBar, FormField, PageHeader, SearchField, Select, StatusBadge } from '../components/ui';

type MockUser = { id: string; name: string; email: string; employeeId: string; role: Role; team: string; location: string; status: 'Active' | 'Inactive'; lastLogin: string };
const users: MockUser[] = [
  { id: 'usr-001', name: 'Ananya Rao', email: 'ananya.rao@royalpackaging.local', employeeId: 'RP-EMP-001', role: 'SUPER_ADMIN', team: 'Operations leadership', location: 'All locations', status: 'Active', lastLogin: 'Today · 09:12' },
  { id: 'usr-002', name: 'Rahul Sharma', email: 'rahul.sharma@royalpackaging.local', employeeId: 'RP-EMP-018', role: 'SUPERVISOR', team: 'Warehouse operations', location: 'Bengaluru · D1', status: 'Active', lastLogin: 'Today · 08:46' },
  { id: 'usr-003', name: 'Meera Nair', email: 'meera.nair@royalpackaging.local', employeeId: 'RP-EMP-024', role: 'EMPLOYEE', team: 'Warehouse operations', location: 'Bengaluru · D1', status: 'Active', lastLogin: 'Today · 07:58' },
  { id: 'usr-004', name: 'Vikram Iyer', email: 'vikram.iyer@royalpackaging.local', employeeId: 'RP-EMP-031', role: 'ADMIN', team: 'Operations leadership', location: 'Bengaluru · D2', status: 'Active', lastLogin: 'Yesterday · 17:20' },
];
const roleDescriptions: Record<Role, string> = { SUPER_ADMIN: 'Full configuration and workspace access.', ADMIN: 'Operational management and finance access.', SUPERVISOR: 'Team operations, verification, and KPI access.', EMPLOYEE: 'Own work, tasks, KPI, and incentive access.' };
const permissionModules = ['EMPLOYEES', 'USERS', 'TASKS', 'WAREHOUSE', 'LOADING_UNLOADING', 'KPI', 'VERIFICATION', 'INCENTIVES', 'PAYROLL', 'REPORTS', 'AUDIT', 'SETTINGS'];
const scopeDescriptions: Record<DataScope, string> = { OWN: 'Records belonging to the current user.', TEAM: 'Records belonging to the current team.', DEPARTMENT: 'Records belonging to the department.', LOCATION: 'Records associated with a location.', ORGANIZATION: 'Organization-wide records.', CUSTOM: 'Specific configured teams, departments, locations, or employees.' };

function AccessNotice() { return <DemoNotice>RBAC configuration is a frontend preview. The backend remains authoritative for users, permissions, and data scope enforcement.</DemoNotice>; }

export function UsersPage() {
  const [query, setQuery] = useState(''); const [role, setRole] = useState('all'); const [status, setStatus] = useState('all'); const navigate = useNavigate();
  const list = users.filter((user) => (!query || `${user.name} ${user.email} ${user.employeeId}`.toLowerCase().includes(query.toLowerCase())) && (role === 'all' || user.role === role) && (status === 'all' || user.status === status));
  return <><PageHeader eyebrow="Access control" title="Users" description="Review workspace identities, assigned roles, and effective access context." actions={<Button disabled title="User creation requires the backend identity contract"><Plus size={15} /> Add user</Button>} /><AccessNotice /><FilterBar resultLabel={`${list.length} of ${users.length} users`}><SearchField placeholder="Search name, email, or employee ID" value={query} onChange={setQuery} /><Select aria-label="Filter user role" value={role} onChange={(event) => setRole(event.target.value)}><option value="all">All roles</option>{(['SUPER_ADMIN', 'ADMIN', 'SUPERVISOR', 'EMPLOYEE'] as Role[]).map((item) => <option key={item}>{item}</option>)}</Select><Select aria-label="Filter user status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option>Active</option><option>Inactive</option></Select></FilterBar><Card><DataTable caption="Workspace users" headers={['User', 'Employee ID', 'Status', 'Role', 'Team', 'Location', 'Last login', '']} rows={list.map((user) => [<button className="table-link person-cell" onClick={() => navigate(`${routes.users}/${user.id}`)}><span className="avatar avatar-indigo">{user.name.slice(0, 2).toUpperCase()}</span><span><strong>{user.name}</strong><small>{user.email}</small></span></button>, <span className="mono">{user.employeeId}</span>, <StatusBadge status={user.status} />, user.role, user.team, user.location, user.lastLogin, <ActionMenu items={[{ label: 'View access', onClick: () => navigate(`${routes.users}/${user.id}`) }, { label: 'Edit user', permission: { module: 'ACCESS_CONTROL', action: 'EDIT' }, onClick: () => undefined }, { label: user.role === 'SUPER_ADMIN' ? 'Remove SUPER_ADMIN (protected)' : 'Deactivate user', danger: true, onClick: () => undefined }]} />])} empty={<EmptyState icon={Users} title="No users found" description="Try another name, role, or status filter." />} /></Card></>;
}

export function RolesPage() {
  const [selected, setSelected] = useState<Role>('SUPERVISOR'); const [customName, setCustomName] = useState(''); const [saved, setSaved] = useState(false);
  const roles = (['SUPER_ADMIN', 'ADMIN', 'SUPERVISOR', 'EMPLOYEE'] as Role[]);
  const permissions = rolePermissions(selected).filter((item) => item.includes(':') && item.includes(':') && /^[A-Z_]+:/.test(item));
  const grouped = permissionModules.map((module) => ({ module, actions: PERMISSION_ACTIONS.filter((action) => permissions.includes(`${module}:${action}`)) })).filter((item) => item.actions.length);
  return <><PageHeader eyebrow="Access control" title="Roles" description="Manage role definitions and preview their effective permission set." actions={<Button disabled title="Role persistence requires the backend contract"><Plus size={15} /> Create role</Button>} /><AccessNotice /><div className="detail-grid"><Card><div className="section-heading"><h2>Role catalog</h2><Badge tone="neutral">{roles.length} system roles</Badge></div><DataTable headers={['Role', 'Description', 'Users', 'Status', '']} rows={roles.map((role) => [<button className="table-link" onClick={() => { setSelected(role); setSaved(false); }}>{role}</button>, roleDescriptions[role], users.filter((user) => user.role === role).length, <StatusBadge status="Active" />, <ActionMenu items={[{ label: 'Edit role', permission: { module: 'ACCESS_CONTROL', action: 'EDIT' }, onClick: () => setSelected(role) }, { label: role === 'SUPER_ADMIN' ? 'Deactivate (protected)' : 'Deactivate role', danger: true, onClick: () => undefined }]} />])} /></Card><Card><div className="section-heading"><div><span className="section-kicker">Role editor</span><h2>{selected}</h2></div><Badge tone="info">Preview</Badge></div><form onSubmit={(event) => { event.preventDefault(); setSaved(true); }}><FormField label="Role name"><input className="input" value={selected} readOnly /></FormField><FormField label="Description"><input className="input" value={roleDescriptions[selected]} readOnly /></FormField><FormField label="Default data scope"><Select aria-label="Default data scope" defaultValue={selected === 'EMPLOYEE' ? 'OWN' : selected === 'SUPERVISOR' ? 'TEAM' : 'ORGANIZATION'}><option>OWN</option><option>TEAM</option><option>DEPARTMENT</option><option>LOCATION</option><option>ORGANIZATION</option><option>CUSTOM</option></Select></FormField><div className="section-heading"><h3>Permission matrix</h3><small>Union of granted capabilities</small></div><div className="permission-list">{grouped.map(({ module, actions }) => <div className="permission-row" key={module}><strong>{module}</strong><span>{actions.map((action) => <Badge tone="success" key={action}><Check size={12} /> {action}</Badge>)}</span></div>)}</div>{saved && <Alert tone="success" title="Preview saved">No server-side role was changed.</Alert>}<Button type="submit">Save preview</Button></form><FormField label="Custom role name" hint="Custom roles are supported conceptually; persistence is backend-dependent."><input className="input" value={customName} onChange={(event) => setCustomName(event.target.value)} placeholder="Warehouse Lead" /></FormField></Card></div></>;
}

export function PermissionsPage() { return <><PageHeader eyebrow="Access control" title="Permissions" description="Reference catalog of system capabilities available to role definitions." /><AccessNotice /><div className="permission-list">{permissionModules.map((module) => <Card key={module}><div className="section-heading"><div><span className="section-kicker">Resource</span><h2>{module}</h2></div><Badge tone="neutral">{PERMISSION_ACTIONS.length} actions</Badge></div><div className="permission-row">{PERMISSION_ACTIONS.map((action) => <span key={action}><Badge tone="info">{action}</Badge><small>{action === 'VIEW' ? `View ${module.toLowerCase()} records` : `${action.toLowerCase()} ${module.toLowerCase()}`}</small></span>)}</div></Card>)}</div></>; }

export function ScopesPage() { const [scope, setScope] = useState<DataScope>('TEAM'); const [saved, setSaved] = useState(false); return <><PageHeader eyebrow="Access control" title="Data scopes" description="Configure the context attached to permission assignments." /><AccessNotice /><div className="detail-grid"><Card><div className="section-heading"><h2>Scope catalog</h2><Badge tone="neutral">{DATA_SCOPES.length} scopes</Badge></div><DataTable headers={['Scope', 'Meaning', '']} rows={DATA_SCOPES.map((item) => [<button className="table-link" onClick={() => { setScope(item); setSaved(false); }}>{item}</button>, scopeDescriptions[item], <StatusBadge status={item === scope ? 'Selected' : 'Available'} />])} /></Card><Card><div className="section-heading"><div><span className="section-kicker">Scope configuration</span><h2>{scope}</h2></div></div><p className="body-copy">{scopeDescriptions[scope]}</p><FormField label="Scope"><Select aria-label="Scope selection" value={scope} onChange={(event) => { setScope(event.target.value as DataScope); setSaved(false); }}>{DATA_SCOPES.map((item) => <option key={item}>{item}</option>)}</Select></FormField>{scope === 'CUSTOM' && <><FormField label="Scope name"><input className="input" placeholder="Bengaluru warehouse team" /></FormField><FormField label="Included locations"><input className="input" placeholder="D1, D2" /></FormField></>}{saved && <Alert tone="success" title="Preview saved">No server-side scope policy was changed.</Alert>}<Button onClick={() => setSaved(true)}>Save preview</Button></Card></div></>; }

export function UserAccessPage() { const user = users[1]; const effective = rolePermissions(user.role).filter((item) => /^[A-Z_]+:/.test(item)); const grouped = effective.reduce<Record<string, string[]>>((result, item) => { const [module, action] = item.split(':'); (result[module] ??= []).push(action); return result; }, {}); return <><PageHeader breadcrumbs={['Users', user.name]} eyebrow="Effective access" title={user.name} description="Preview the union of role permissions and session scope." /><AccessNotice /><div className="detail-grid"><Card><div className="section-heading"><h2>User</h2><StatusBadge status={user.status} /></div><div className="detail-facts"><span><small>Email</small><strong>{user.email}</strong></span><span><small>Employee ID</small><strong>{user.employeeId}</strong></span><span><small>Team</small><strong>{user.team}</strong></span><span><small>Location</small><strong>{user.location}</strong></span></div></Card><Card><div className="section-heading"><h2>Assigned roles</h2><Button variant="secondary" disabled><Plus size={15} /> Assign role</Button></div><Badge tone="info">{user.role}</Badge><h2>Effective permissions</h2><div className="permission-list">{Object.entries(grouped).map(([module, actions]) => <div className="permission-row" key={module}><strong>{module}</strong><span>{actions.map((action) => <Badge tone="success" key={action}>{action}</Badge>)}</span></div>)}</div><h2>Effective scope</h2><Badge tone="warning">TEAM</Badge></Card></div></>; }

export function RbacNotFound() { return <Card className="empty-panel not-found"><EmptyState icon={Archive} title="RBAC view not found" description="This access-control surface has not been defined." action={<a className="button button-primary" href={routes.users}>Back to users</a>} /></Card>; }
